language: cpp
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
    - os: osx
      osx_image: xcode9.2
      sudo: required
      compiler: clang

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq; fi

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -qq g++-7 wget; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 90
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then CC=gcc-7 && CXX=g++-7
  - sudo mkdir -p /usr/local/include/nlohmann
  - sudo wget -O /usr/local/include/nlohmann/json.hpp https://raw.githubusercontent.com/nlohmann/json/develop/src/json.hpp
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -qq libfreetype6-dev libjpeg-turbo8-dev libx11-dev libxrandr-dev xcb libgl1-mesa-dev flac libflac-dev libogg-dev libvorbis-dev libvorbisenc2 libvorbisfile3 libopenal-dev libudev-dev; fi
  - git clone --recursive https://github.com/SFML/SFML.git
  - cd SFML
  - git checkout tags/2.4.2
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then CMAKE_CXX_COMPILER="/usr/bin/clang++"" && CMAKE_C_COMPILER="/usr/bin/clang" && CMAKE_CXX_FLAGS="-stdlib=libc++" && CMAKE_C_FLAGS="-stdlib=libc++"; fi
  - cmake .. -DSFML_STATIC=true
  - make
  - sudo make install
  - cd ../..

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make static; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then make llstatic; fi