language: cpp
compiler: clang
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode9.2

#before_install:
#  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
#  - sudo apt-get update -qq

install:
#  - sudo apt-get install -qq g++-7 wget
#  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90
#  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 90
#  - CC=gcc-7 && CXX=g++-7
  - sudo mkdir -p /usr/include/nlohmann
  - sudo wget -O /usr/include/nlohmann/json.hpp https://raw.githubusercontent.com/nlohmann/json/develop/src/json.hpp
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -qq libfreetype6-dev libjpeg-turbo8-dev libx11-dev libxrandr-dev xcb libgl1-mesa-dev flac libflac-dev libogg-dev libvorbis-dev libvorbisenc2 libvorbisfile3 libopenal-dev libudev-dev; fi
  - git clone --recursive https://github.com/SFML/SFML.git
  - mkdir -p SFML/build
  - cd SFML/build
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then CMAKE_CXX_FLAGS="-stdlib=libc++" && CMAKE_C_FLAGS="-stdlib=libc++"; fi
  - cmake .. -DSFML_STATIC=true
  - make
  - sudo make install
  - cd ../..

script:
  - make llstatic